## 1. Import libraries

In [1]:
import pandas as pd
import numpy as np
import os

## 2. Flat file digestion
STRUCTURED DATASET FROM CDC WONDER

In [2]:
# load csv file
df = pd.read_csv('../data/raw/YEAR_STATE_1999_2020.csv')

## 3. Inspect and validate

In [3]:
# check data
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1189 entries, 0 to 1188
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Notes       67 non-null     str
 1   Year        1122 non-null   float64
 2   Year Code   1122 non-null   float64
 3   State       1122 non-null   str
 4   State Code  1122 non-null   float64
 5   Deaths      1122 non-null   str
 6   Population  1122 non-null   float64
 7   Crude Rate  1122 non-null   str
dtypes: float64(4), str(4)
memory usage: 97.3 KB

In [4]:
# check first 5 rows
df.head()

,Notes,Year,Year Code,State,State Code,Deaths,Population,Crude Rate
0,NaN,1999.0,1999.0,Alabama,1.0,39,4430141.0,0.9
1,NaN,1999.0,1999.0,Alaska,2.0,28,624779.0,4.5
2,NaN,1999.0,1999.0,Arizona,4.0,250,5023823.0,5.0
3,NaN,1999.0,1999.0,Arkansas,5.0,29,2651860.0,1.1
4,NaN,1999.0,1999.0,California,6.0,1598,33499204.0,4.8

In [5]:
# check last 5 rows
df.tail()

,Notes,Year,Year Code,State,State Code,Deaths,Population,Crude Rate
1184,were available at the time of release.,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1185,8. The population figures used in the calculat...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1186,resident population that is under one year of ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1187,9. Changes to cause of death classification af...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1188,http://wonder.cdc.gov/wonder/help/mcd.html#ICD...,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Check missing values

In [6]:
df.isna().sum()

Notes         1122
Year            67
Year Code       67
State           67
State Code      67
Deaths          67
Population      67
Crude Rate      67
dtype: int64

### Check duplicate rows

In [7]:
df.duplicated().sum()

np.int64(5)

In [8]:
df[df.duplicated(keep = False)]

     Notes  Year  Year Code State  State Code Deaths  Population Crude Rate
1122   ---   NaN        NaN   NaN         NaN    NaN         NaN        NaN
1134   ---   NaN        NaN   NaN         NaN    NaN         NaN        NaN
1136   ---   NaN        NaN   NaN         NaN    NaN         NaN        NaN
1138   ---   NaN        NaN   NaN         NaN    NaN         NaN        NaN
1143   ---   NaN        NaN   NaN         NaN    NaN         NaN        NaN
1147   ---   NaN        NaN   NaN         NaN    NaN         NaN        NaN

### Check count of unique values across all columns

In [9]:
# return no. of unique values in 'Notes' column
df.nunique()

Notes           62
Year            22
Year Code       22
State           51
State Code      51
Deaths         685
Population    1121
Crude Rate     265
dtype: int64

### Check unique values in `Notes`

In [10]:
# return no. of unique values in 'Notes' column
df['Notes'].nunique()

62

In [11]:
# return list of unique values in 'Notes' column
list(df['Notes'].unique())

[nan,
 '---',
 'Dataset: Multiple Cause of Death, 1999-2020',
 'Query Parameters:',
 'Title: MCD_YEAR_STATE_ALL',
 'MCD - ICD-10 Codes: T40.0 (Opium); T40.1 (Heroin); T40.2 (Other opioids); T40.3 (Methadone); T40.4 (Other synthetic narcotics);',
 'T40.6 (Other and unspecified narcotics)',
 'Group By: Year; State',
 'Show Totals: Disabled',
 'Show Zero Values: True',
 'Show Suppressed: True',
 'Calculate Rates Per: 100,000',
 'Rate Options: Default intercensal populations for years 2001-2009 (except Infant Age Groups)',
 'Help: See http://wonder.cdc.gov/wonder/help/mcd.html for more information.',
 'Query Date: Jun 2, 2026 5:19:32 AM',
 'Suggested Citation: Centers for Disease Control and Prevention, National Center for Health Statistics. National Vital Statistics',
 'System, Mortality 1999-2020 on CDC WONDER Online Database, released in 2021. Data are from the Multiple Cause of Death Files,',
 '1999-2020, as compiled from data provided by the 57 vital statistics jurisdictions through the Vital Statistics Cooperative',
 'Program. Accessed at http://wonder.cdc.gov/mcd-icd10.html on Jun 2, 2026 5:19:32 AM',
 'Messages:',
 '1. Totals are not available for these results due to suppression constraints. More Information:',
 'http://wonder.cdc.gov/wonder/help/faq.html#Privacy.',
 'Caveats:',
 '1. As of April 3, 2017, the underlying cause of death has been revised for 125 deaths in 2014. More information:',
 'http://wonder.cdc.gov/wonder/help/mcd.html#2014-Revision.',
 '2. Circumstances in Georgia for the years 2008 and 2009 have resulted in unusually high death counts for the ICD-10 cause of',
 'death code R99, "Other ill-defined and unspecified causes of mortality." Caution should be used in interpreting these data.',
 'More information: http://wonder.cdc.gov/wonder/help/mcd.html#Georgia-Reporting-Anomalies.',
 '3. Circumstances in New Jersey for the year 2009 have resulted in unusually high death counts for the ICD-10 cause of death code',
 'R99, "Other ill-defined and unspecified causes of mortality" and therefore unusually low death counts in other ICD-10 codes,',
 'most notably R95, "Sudden Infant Death Syndrome" and X40-X49, "Unintentional poisoning." Caution should be used in',
 'interpreting these data. More information: http://wonder.cdc.gov/wonder/help/mcd.html#New-Jersey-Reporting-Anomalies.',
 '4. Circumstances in California resulted in unusually high death counts for the ICD-10 cause of death code R99, "Other',
 'ill-defined and unspecified causes of mortality" for deaths occurring in years 2000 and 2001. Caution should be used in',
 'interpreting these data. More information: http://wonder.cdc.gov/wonder/help/mcd.html#California-Reporting-Anomalies.',
 '5. Data are Suppressed when the data meet the criteria for confidentiality constraints. More information:',
 'http://wonder.cdc.gov/wonder/help/mcd.html#Assurance of Confidentiality.',
 '6. Death rates are flagged as Unreliable when the rate is calculated with a numerator of 20 or less. More information:',
 'http://wonder.cdc.gov/wonder/help/mcd.html#Unreliable.',
 '7. The population figures for year 2020 are bridged-race estimates of the July 1 resident population, from the Vintage 2020',
 'postcensal series released by NCHS on September 22, 2021. The population figures for year 2019 are bridged-race estimates of the',
 'July 1 resident population, from the Vintage 2019 postcensal series released by NCHS on July 9, 2020. The population figures for',
 'year 2018 are bridged-race estimates of the July 1 resident population, from the Vintage 2018 postcensal series released by NCHS',
 'on June 25, 2019. The population figures for year 2017 are bridged-race estimates of the July 1 resident population, from the',
 'Vintage 2017 postcensal series released by NCHS on June 27, 2018. The population figures for year 2016 are bridged-race',
 'estimates of the July 1 resident population, from the Vintage 2016 postcensal series released by NCHS on June 26, 2017. The',
 'population figures for year 2015 are bridged-race estimates of the July 1 resident population, from the Vintage 2015 postcensal',
 'series released by NCHS on June 28, 2016. The population figures for year 2014 are bridged-race estimates of the July 1 resident',
 'population, from the Vintage 2014 postcensal series released by NCHS on June 30, 2015. The population figures for year 2013 are',
 'bridged-race estimates of the July 1 resident population, from the Vintage 2013 postcensal series released by NCHS on June 26,',
 '2014. The population figures for year 2012 are bridged-race estimates of the July 1 resident population, from the Vintage 2012',
 'postcensal series released by NCHS on June 13, 2013. Population figures for 2011 are bridged-race estimates of the July 1',
 'resident population, from the county-level postcensal Vintage 2011 series released by NCHS on July 18, 2012. Population figures',
 'for 2010 are April 1 Census counts. The population figures for years 2001 - 2009, are bridged-race estimates of the July 1',
 'resident population, from the revised intercensal county-level 2000 - 2009 series released by NCHS on October 26, 2012.',
 'Population figures for 2000 are April 1 Census counts. Population figures for 1999 are from the 1990-1999 intercensal series of',
 'July 1 estimates. Population figures for Infant Age Groups are the number of live births. <br/><b>Note:</b> Rates and population',
 'figures for years 2001 - 2009 differ slightly from previously published reports, due to use of the population estimates which',
 'were available at the time of release.',
 "8. The population figures used in the calculation of death rates for the age group 'under 1 year' are the estimates of the",
 'resident population that is under one year of age. More information: http://wonder.cdc.gov/wonder/help/mcd.html#Age Group.',
 '9. Changes to cause of death classification affect reporting trends. More information:',
 'http://wonder.cdc.gov/wonder/help/mcd.html#ICD-10 Changes.']

In [12]:
# return data where 'Notes' column has text
df[df['Notes'].notna()]

,Notes,Year,Year Code,State,State Code,Deaths,Population,Crude Rate
1122,---,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1123,"Dataset: Multiple Cause of Death, 1999-2020",NaN,NaN,NaN,NaN,NaN,NaN,NaN
1124,Query Parameters:,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1125,Title: MCD_YEAR_STATE_ALL,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1126,MCD - ICD-10 Codes: T40.0 (Opium); T40.1 (Hero...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
1184,were available at the time of release.,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1185,8. The population figures used in the calculat...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1186,resident population that is under one year of ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1187,9. Changes to cause of death classification af...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1188,http://wonder.cdc.gov/wonder/help/mcd.html#ICD...,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
# return indexes of rows where 'Notes' column has text
df[df['Notes'].notna()].index

RangeIndex(start=1122, stop=1189, step=1)

In [14]:
# return index of first row where 'Notes' column has text
df[df['Notes'].notna()].index[0]

1122

### Drop metadata

In [15]:
# assign first index where 'Notes' has text to `cutoff`
cutoff = df[df['Notes'].notna()].index[0]
cutoff

1122

In [16]:
# return df_working excluding rows where 'Notes' column has text
# check last 5 rows
df_working = df.iloc[:cutoff]
df_working.tail()

,Notes,Year,Year Code,State,State Code,Deaths,Population,Crude Rate
1117,NaN,2020.0,2020.0,Virginia,51.0,1917,8590563.0,22.3
1118,NaN,2020.0,2020.0,Washington,53.0,1221,7693612.0,15.9
1119,NaN,2020.0,2020.0,West Virginia,54.0,1179,1784787.0,66.1
1120,NaN,2020.0,2020.0,Wisconsin,55.0,1270,5832655.0,21.8
1121,NaN,2020.0,2020.0,Wyoming,56.0,66,582328.0,11.3

**ADD TO REUSABLE FUNCTION**

In [17]:
# check df_working
df_working.info()

<class 'pandas.DataFrame'>
RangeIndex: 1122 entries, 0 to 1121
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Notes       0 non-null      str
 1   Year        1122 non-null   float64
 2   Year Code   1122 non-null   float64
 3   State       1122 non-null   str
 4   State Code  1122 non-null   float64
 5   Deaths      1122 non-null   str
 6   Population  1122 non-null   float64
 7   Crude Rate  1122 non-null   str
dtypes: float64(4), str(4)
memory usage: 87.5 KB

### Check missing values

In [18]:
df_working.isna().sum()

Notes         1122
Year             0
Year Code        0
State            0
State Code       0
Deaths           0
Population       0
Crude Rate       0
dtype: int64

### Check duplicates

In [19]:
df_working.duplicated().sum()

np.int64(0)

### Drop unnecessary columns

In [20]:
# drop 'Notes' column from df_working
df_working = df_working.drop(columns = 'Notes')

**ADD TO REUSABLE FUNCTION**

In [21]:
# check df_working
df_working.info()

<class 'pandas.DataFrame'>
RangeIndex: 1122 entries, 0 to 1121
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Year        1122 non-null   float64
 1   Year Code   1122 non-null   float64
 2   State       1122 non-null   str
 3   State Code  1122 non-null   float64
 4   Deaths      1122 non-null   str
 5   Population  1122 non-null   float64
 6   Crude Rate  1122 non-null   str
dtypes: float64(4), str(3)
memory usage: 78.6 KB

## 4. Create reusable function to remove metadata

In [22]:
def remove_metadata(filepath: str) -> pd.DataFrame:
    
    # load file
    df = pd.read_csv(filepath, dtype=str)
    
    # assign index of first row with metadata to cutoff
    cutoff = df[df['Notes'].notna()].index[0]
    
    # drop rows with metadata
    df_sans_metadata = df.iloc[:cutoff]
    
    # drop 'Notes' column
    df_sans_metadata = df_sans_metadata.drop(columns='Notes')
    
    return df_sans_metadata

# load single file
filepath = '../data/raw/YEAR_STATE_1999_2020.csv'
df_clean = remove_metadata(filepath)

print(f"Shape: {df_clean.shape}")
print(f"Year range: {df_clean['Year'].min()} – {df_clean['Year'].max()}")

# write to processed directory
df_clean.to_csv(
    '../data/processed/YEAR_STATE_1999_2020_preprocessed.csv', 
    index = False
)

print('Saved: ../data/processed/YEAR_STATE_1999_2020_preprocessed.csv')

Shape: (1122, 7)
Year range: 1999 – 2020
Saved: ../data/processed/YEAR_STATE_1999_2020_preprocessed.csv

### Confirm file

In [23]:
os.path.exists('../data/processed/YEAR_STATE_1999_2020_preprocessed.csv')

True

## 5. Inspect and validate

In [24]:
df_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 1122 entries, 0 to 1121
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Year        1122 non-null   str
 1   Year Code   1122 non-null   str
 2   State       1122 non-null   str
 3   State Code  1122 non-null   str
 4   Deaths      1122 non-null   str
 5   Population  1122 non-null   str
 6   Crude Rate  1122 non-null   str
dtypes: str(7)
memory usage: 97.8 KB

In [25]:
df_clean.head()

   Year Year Code       State State Code Deaths Population Crude Rate
0  1999      1999     Alabama         01     39    4430141        0.9
1  1999      1999      Alaska         02     28     624779        4.5
2  1999      1999     Arizona         04    250    5023823        5.0
3  1999      1999    Arkansas         05     29    2651860        1.1
4  1999      1999  California         06   1598   33499204        4.8

In [26]:
df_clean.tail()

      Year Year Code          State State Code Deaths Population Crude Rate
1117  2020      2020       Virginia         51   1917    8590563       22.3
1118  2020      2020     Washington         53   1221    7693612       15.9
1119  2020      2020  West Virginia         54   1179    1784787       66.1
1120  2020      2020      Wisconsin         55   1270    5832655       21.8
1121  2020      2020        Wyoming         56     66     582328       11.3

In [27]:
df_clean.isna().sum()

Year          0
Year Code     0
State         0
State Code    0
Deaths        0
Population    0
Crude Rate    0
dtype: int64

In [28]:
df_clean.duplicated().sum()

np.int64(0)

In [29]:
df_clean.nunique()

Year            22
Year Code       22
State           51
State Code      51
Deaths         685
Population    1121
Crude Rate     265
dtype: int64

## 6. Column validation and cleaning

### `Year` and `YEAR CODE`

In [30]:
# check unique values in 'Year'
df_clean['Year'].unique()

<ArrowStringArray>
['1999', '2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007',
 '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016',
 '2017', '2018', '2019', '2020']
Length: 22, dtype: str

In [31]:
# check unique values in 'Year Code'
df_clean['Year Code'].unique()

<ArrowStringArray>
['1999', '2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007',
 '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016',
 '2017', '2018', '2019', '2020']
Length: 22, dtype: str

In [32]:
# check if 'Year' == 'Year Code'
(df_clean['Year'] == df_clean['Year Code']).all()

np.True_

In [33]:
# convert 'Year' column to numerical values
df_clean['Year'] = df_clean['Year'].astype('int64')

**ADD TO REUSABLE FUNCTION**

In [34]:
# drop 'Year Code' column
df_clean.drop(columns = ['Year Code'], inplace = True)

**ADD TO REUSABLE FUNCTION**

In [35]:
# check df_clean
df_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 1122 entries, 0 to 1121
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Year        1122 non-null   int64
 1   State       1122 non-null   str
 2   State Code  1122 non-null   str
 3   Deaths      1122 non-null   str
 4   Population  1122 non-null   str
 5   Crude Rate  1122 non-null   str
dtypes: int64(1), str(5)
memory usage: 80.0 KB

### `State` and `State Code`

In [36]:
# check unique values in 'State'
df_clean['State'].unique()

<ArrowStringArray>
[             'Alabama',               'Alaska',              'Arizona',
             'Arkansas',           'California',             'Colorado',
          'Connecticut',             'Delaware', 'District of Columbia',
              'Florida',              'Georgia',               'Hawaii',
                'Idaho',             'Illinois',              'Indiana',
                 'Iowa',               'Kansas',             'Kentucky',
            'Louisiana',                'Maine',             'Maryland',
        'Massachusetts',             'Michigan',            'Minnesota',
          'Mississippi',             'Missouri',              'Montana',
             'Nebraska',               'Nevada',        'New Hampshire',
           'New Jersey',           'New Mexico',             'New York',
       'North Carolina',         'North Dakota',                 'Ohio',
             'Oklahoma',               'Oregon',         'Pennsylvania',
         'Rhode Island',       'South Carolina',         'South Dakota',
            'Tennessee',                'Texas',                 'Utah',
              'Vermont',             'Virginia',           'Washington',
        'West Virginia',            'Wisconsin',              'Wyoming']
Length: 51, dtype: str

In [37]:
# check unique values in 'State Code'
df_clean['State Code'].unique()

<ArrowStringArray>
['01', '02', '04', '05', '06', '08', '09', '10', '11', '12', '13', '15', '16',
 '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29',
 '30', '31', '32', '33', '34', '35', '36', '37', '38', '39', '40', '41', '42',
 '44', '45', '46', '47', '48', '49', '50', '51', '53', '54', '55', '56']
Length: 51, dtype: str

In [38]:
# check df_clean
df_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 1122 entries, 0 to 1121
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Year        1122 non-null   int64
 1   State       1122 non-null   str
 2   State Code  1122 non-null   str
 3   Deaths      1122 non-null   str
 4   Population  1122 non-null   str
 5   Crude Rate  1122 non-null   str
dtypes: int64(1), str(5)
memory usage: 80.0 KB

### `Deaths`

In [39]:
# check total number of unique values in 'Deaths' column
df_clean['Deaths'].nunique()

685

In [40]:
# check first five rows in 'Deaths' column
df_clean['Deaths'].head()

0      39
1      28
2     250
3      29
4    1598
Name: Deaths, dtype: str

In [41]:
# check last five rows in 'Deaths' column
df_clean['Deaths'].tail()

1117    1917
1118    1221
1119    1179
1120    1270
1121      66
Name: Deaths, dtype: str

In [42]:
# convert values in 'Deaths' column into numerical values
df_clean['Deaths'] = df_clean['Deaths'].astype('int64')

ValueError: invalid literal for int() with base 10: 'Suppressed'

**UNEXPECTED ERROR - SOME VALUES CANNOT BE CONVERTED INTO NUMERICAL VALUE**

In [43]:
# convert values in 'Deaths' column to numerical values, otherwise converts to NaN
pd.to_numeric(df_clean['Deaths'], errors = 'coerce')

0         39.0
1         28.0
2        250.0
3         29.0
4       1598.0
         ...
1117    1917.0
1118    1221.0
1119    1179.0
1120    1270.0
1121      66.0
Name: Deaths, Length: 1122, dtype: float64

In [44]:
# returns values from 'Deaths' column where values = NaN (False)
pd.to_numeric(df_clean['Deaths'], errors = 'coerce').isna()

0       False
1       False
2       False
3       False
4       False
        ...
1117    False
1118    False
1119    False
1120    False
1121    False
Name: Deaths, Length: 1122, dtype: bool

In [45]:
# return df_combined where rows where 'Deaths' = NaN
df_clean[pd.to_numeric(df_clean['Deaths'], errors = 'coerce').isna()].head()

    Year         State State Code      Deaths Population  Crude Rate
27  1999      Nebraska         31  Suppressed    1704764  Suppressed
34  1999  North Dakota         38  Suppressed     644259  Suppressed
41  1999  South Dakota         46  Suppressed     750412  Suppressed
50  1999       Wyoming         56  Suppressed     491780  Suppressed
85  2000  North Dakota         38  Suppressed     642200  Suppressed

**THERE ARE OBJECTS IN THE `Deaths` COLUMN WHICH PREVENT NUMERICAL CONVERSION**

In [46]:
# return unique values in 'Deaths' column where NaN is False
(df_clean[pd.to_numeric(df_clean['Deaths'], errors = 'coerce')
    .isna()]['Deaths']
    .unique()
)

<ArrowStringArray>
['Suppressed']
Length: 1, dtype: str

**`Suppressed` PREVENTS NUMERICAL CONVERSION**

In [47]:
# return sum of 'Suppressed' occurrences in 'Deaths' column
(df_clean['Deaths'] == 'Suppressed').sum()

np.int64(13)

**TOTAL OF 13 INSTANCES WHERE 'Deaths' is 'Suppressed'**

In [48]:
# add 'Deaths_Supressed' column before replacing 'Suppressed' with NaN
df_clean['Deaths_Suppressed'] = df_clean['Deaths'] == 'Suppressed'

**ADD TO REUSABLE FUNCTION**

In [49]:
# check unique values in `Deaths_Suppressed` column
df_clean['Deaths_Suppressed'].unique()

array([False,  True])

In [50]:
# check df_clean
df_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 1122 entries, 0 to 1121
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Year               1122 non-null   int64
 1   State              1122 non-null   str
 2   State Code         1122 non-null   str
 3   Deaths             1122 non-null   str
 4   Population         1122 non-null   str
 5   Crude Rate         1122 non-null   str
 6   Deaths_Suppressed  1122 non-null   bool
dtypes: bool(1), int64(1), str(5)
memory usage: 81.1 KB

In [51]:
# return values in 'Deaths' colummn where 'Deaths' is 'Suppressed'
df_clean.loc[df_clean['Deaths'] == 'Suppressed', 'Deaths']

27     Suppressed
34     Suppressed
41     Suppressed
50     Suppressed
85     Suppressed
92     Suppressed
136    Suppressed
152    Suppressed
154    Suppressed
254    Suppressed
340    Suppressed
391    Suppressed
697    Suppressed
Name: Deaths, dtype: str

In [52]:
# assign NaN to 'Suppressed' values in 'Deaths' column 
df_clean.loc[df_clean['Deaths'] == 'Suppressed', 'Deaths'] = np.nan

**ADD TO REUSABLE FUNCITON**

In [53]:
# return sum of NaN occurences in 'Deaths' column
df_clean['Deaths'].isna().sum()

np.int64(13)

In [54]:
# check df_clean
df_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 1122 entries, 0 to 1121
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Year               1122 non-null   int64
 1   State              1122 non-null   str
 2   State Code         1122 non-null   str
 3   Deaths             1109 non-null   str
 4   Population         1122 non-null   str
 5   Crude Rate         1122 non-null   str
 6   Deaths_Suppressed  1122 non-null   bool
dtypes: bool(1), int64(1), str(5)
memory usage: 80.9 KB

In [55]:
# convert values in 'Deaths' column into numerical values
df_clean['Deaths'] = pd.to_numeric(df_clean['Deaths'], errors='coerce')
df_clean['Deaths'].dtype

dtype('float64')

**ADD TO REUSABLE FUNCTION**

In [56]:
# check df_clean
df_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 1122 entries, 0 to 1121
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Year               1122 non-null   int64
 1   State              1122 non-null   str
 2   State Code         1122 non-null   str
 3   Deaths             1109 non-null   float64
 4   Population         1122 non-null   str
 5   Crude Rate         1122 non-null   str
 6   Deaths_Suppressed  1122 non-null   bool
dtypes: bool(1), float64(1), int64(1), str(4)
memory usage: 77.7 KB

### `Population`

In [57]:
# convert values in 'Population' column into numerical values
df_clean['Population'] = df_clean['Population'].astype('int64')

In [58]:
# check df_clean
df_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 1122 entries, 0 to 1121
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Year               1122 non-null   int64
 1   State              1122 non-null   str
 2   State Code         1122 non-null   str
 3   Deaths             1109 non-null   float64
 4   Population         1122 non-null   int64
 5   Crude Rate         1122 non-null   str
 6   Deaths_Suppressed  1122 non-null   bool
dtypes: bool(1), float64(1), int64(2), str(3)
memory usage: 69.8 KB

### `Crude Rate`

In [59]:
# check unique values for 'Crude Rate'
df_clean['Crude Rate'].nunique()

265

In [60]:
# convert values in 'Crude Rate' column into numerical values
df_clean['Crude Rate'] = df_clean['Crude Rate'].astype('float64')

ValueError: could not convert string to float: 'Unreliable'

**UNEXPECTED ERROR - SOME VALUES CANNOT BE CONVERTED INTO NUMERICAL VALUE**

In [61]:
# return unique values in 'Crude Rate' column where NaN is False
(df_clean[pd.to_numeric(df_clean['Crude Rate'], errors='coerce')
    .isna()]['Crude Rate']
    .unique()
)

<ArrowStringArray>
['Unreliable', 'Suppressed']
Length: 2, dtype: str

**`Unreliable` AND `Suppressed` PREVENTS NUMERICAL CONVERSION**

In [62]:
# return sum counts of 'Suppressed' + 'Unreliable'
df_clean['Crude Rate'].isin(['Suppressed', 'Unreliable']).sum()

np.int64(44)

In [63]:
# return counts where 'Crude Rate' is either 'Unreliable' or 'Suppressed'
(df_clean[pd.to_numeric(df_clean['Crude Rate'], errors='coerce')
    .isna()]['Crude Rate']
    .value_counts()
)

Crude Rate
Unreliable    31
Suppressed    13
Name: count, dtype: int64

**TOTAL OF 44 INSTANCES WHERE 'Crude Rate' is 'Unreliable' or 'Suppressed**

In [64]:
# calculate percentage of 'Unreliable' + 'Suppressed' from 44 total rows
non_numeric = pd.to_numeric(df_clean['Crude Rate'], errors='coerce').isna().sum()

total = len(df_clean)

print(f"{non_numeric / total * 100:.2f}% of 'Crude Rate' is either 'Unreliable' or 'Suppressed'")

3.92% of 'Crude Rate' is either 'Unreliable' or 'Suppressed'

In [65]:
# create 'Crude Rate Calculated' column
df_clean['Crude Rate Calculated'] = (df_clean['Deaths'] / df_clean['Population']) * 100000

**ADD TO REUSUABLE FUNCTION**

In [66]:
# check df_clean
df_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 1122 entries, 0 to 1121
Data columns (total 8 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Year                   1122 non-null   int64
 1   State                  1122 non-null   str
 2   State Code             1122 non-null   str
 3   Deaths                 1109 non-null   float64
 4   Population             1122 non-null   int64
 5   Crude Rate             1122 non-null   str
 6   Deaths_Suppressed      1122 non-null   bool
 7   Crude Rate Calculated  1109 non-null   float64
dtypes: bool(1), float64(2), int64(2), str(3)
memory usage: 78.6 KB

In [67]:
# reset index
df_clean = df_clean.reset_index(drop=True)

**ADD TO REUSUABLE FUNCTION**

## 7. Export cleaned data

In [68]:
print(f"Shape: {df_clean.shape}")
print(f"Year range: {df_clean['Year'].min()} – {df_clean['Year'].max()}")

# write to processed directory
df_clean.to_csv(
    '../data/processed/YEAR_STATE_1999_2020_cleaned.csv', 
    index = False
)

print('Saved: ../data/processed/YEAR_STATE_1999_2020_cleaned.csv')

Shape: (1122, 8)
Year range: 1999 – 2020
Saved: ../data/processed/YEAR_STATE_1999_2020_cleaned.csv

In [69]:
os.path.exists('../data/processed/YEAR_STATE_1999_2020_cleaned.csv')

True