## IMPORT LIBRARIES

In [1]:
import pandas as pd
import os

## FLAT FILE DATA INGESTION (STRUCTURED DATASET FROM CDC WONDER)

In [2]:
# LOAD DATA
df = pd.read_csv('../data/raw/underlying_cause_of_death_1999_2020.csv')

## DATA INSPECTION, VALIDATION, CLEANING

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1219 entries, 0 to 1218
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Notes       97 non-null     str
 1   State       1173 non-null   str
 2   State Code  1173 non-null   float64
 3   Year        1122 non-null   float64
 4   Year Code   1122 non-null   float64
 5   Deaths      1174 non-null   float64
 6   Population  1174 non-null   float64
 7   Crude Rate  1174 non-null   float64
dtypes: float64(6), str(2)
memory usage: 90.4 KB

In [4]:
df.head()

,Notes,State,State Code,Year,Year Code,Deaths,Population,Crude Rate
0,NaN,Alabama,1.0,1999.0,1999.0,44806.0,4430141.0,1011.39
1,NaN,Alabama,1.0,2000.0,2000.0,45062.0,4447100.0,1013.29
2,NaN,Alabama,1.0,2001.0,2001.0,45316.0,4467634.0,1014.32
3,NaN,Alabama,1.0,2002.0,2002.0,46069.0,4480089.0,1028.31
4,NaN,Alabama,1.0,2003.0,2003.0,46716.0,4503491.0,1037.33

In [5]:
df.tail()

,Notes,State,State Code,Year,Year Code,Deaths,Population,Crude Rate
1214,estimates. Population figures for the infant a...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1215,figures for years 2001 - 2009 differ slightly ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1216,were available at the time of release.,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1217,3. The population figures used in the calculat...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1218,resident population that is under one year of ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### CHECK UNIQUE VALUES

In [6]:
df['Notes'].nunique()

42

In [7]:
list(df['Notes'].unique())

[nan,
 'Total',
 '---',
 'Dataset: Underlying Cause of Death, 1999-2020',
 'Query Parameters:',
 'Title: underlying_cause_of_death_1999_2020',
 'Group By: State; Year',
 'Show Totals: True',
 'Show Zero Values: True',
 'Show Suppressed: True',
 'Calculate Rates Per: 100,000',
 'Rate Options: Default intercensal populations for years 2001-2009 (except Infant Age Groups)',
 'Help: See http://wonder.cdc.gov/wonder/help/ucd.html for more information.',
 'Query Date: May 23, 2026 10:19:30 PM',
 'Suggested Citation: Centers for Disease Control and Prevention, National Center for Health Statistics. National Vital Statistics',
 'System, Mortality 1999-2020 on CDC WONDER Online Database, released in 2021. Data are from the Multiple Cause of Death Files,',
 '1999-2020, as compiled from data provided by the 57 vital statistics jurisdictions through the Vital Statistics Cooperative',
 'Program. Accessed at http://wonder.cdc.gov/ucd-icd10.html on May 23, 2026 10:19:30 PM',
 'Caveats:',
 '1. As of April 3, 2017, the underlying cause of death has been revised for 125 deaths in 2014. More information:',
 'http://wonder.cdc.gov/wonder/help/ucd.html#2014-Revision.',
 '2. The population figures for year 2020 are bridged-race estimates of the July 1 resident population, from the Vintage 2020',
 'postcensal series released by NCHS on September 22, 2021. The population figures for year 2019 are bridged-race estimates of the',
 'July 1 resident population, from the Vintage 2019 postcensal series released by NCHS on July 9, 2020. The population figures for',
 'year 2018 are bridged-race estimates of the July 1 resident population, from the Vintage 2018 postcensal series released by NCHS',
 'on June 25, 2019. The population figures for year 2017 are bridged-race estimates of the July 1 resident population, from the',
 'Vintage 2017 postcensal series released by NCHS on June 27, 2018. The population figures for year 2016 are bridged-race',
 'estimates of the July 1 resident population, from the Vintage 2016 postcensal series released by NCHS on June 26, 2017. The',
 'population figures for year 2015 are bridged-race estimates of the July 1 resident population, from the Vintage 2015 postcensal',
 'series released by NCHS on June 28, 2016. The population figures for year 2014 are bridged-race estimates of the July 1 resident',
 'population, from the Vintage 2014 postcensal series released by NCHS on June 30, 2015. The population figures for year 2013 are',
 'bridged-race estimates of the July 1 resident population, from the Vintage 2013 postcensal series released by NCHS on June 26,',
 '2014. The population figures for year 2012 are bridged-race estimates of the July 1 resident population, from the Vintage 2012',
 'postcensal series released by NCHS on June 13, 2013. The population figures for year 2011 are bridged-race estimates of the July',
 '1 resident population, from the Vintage 2011 postcensal series released by NCHS on July 18, 2012. Population figures for 2010',
 'are April 1 Census counts. The population figures for years 2001 - 2009 are bridged-race estimates of the July 1 resident',
 'population, from the revised intercensal county-level 2000 - 2009 series released by NCHS on October 26, 2012. Population',
 'figures for 2000 are April 1 Census counts. Population figures for 1999 are from the 1990-1999 intercensal series of July 1',
 'estimates. Population figures for the infant age groups are the number of live births. <br/><b>Note:</b> Rates and population',
 'figures for years 2001 - 2009 differ slightly from previously published reports, due to use of the population estimates which',
 'were available at the time of release.',
 "3. The population figures used in the calculation of death rates for the age group 'under 1 year' are the estimates of the",
 'resident population that is under one year of age. More information: http://wonder.cdc.gov/wonder/help/ucd.html#Age Group.']

### CHECK FOR MISSING VALUES

In [8]:
df[df['Notes'].notna()].head()

,Notes,State,State Code,Year,Year Code,Deaths,Population,Crude Rate
22,Total,Alabama,1.0,NaN,NaN,1087306.0,103604166.0,1049.48
45,Total,Alaska,2.0,NaN,NaN,82025.0,15300884.0,536.08
68,Total,Arizona,4.0,NaN,NaN,1091130.0,138079425.0,790.22
91,Total,Arkansas,5.0,NaN,NaN,658885.0,63181817.0,1042.84
114,Total,California,6.0,NaN,NaN,5433709.0,815706063.0,666.14

In [9]:
df[df['Notes'].notna()].tail()

,Notes,State,State Code,Year,Year Code,Deaths,Population,Crude Rate
1214,estimates. Population figures for the infant a...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1215,figures for years 2001 - 2009 differ slightly ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1216,were available at the time of release.,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1217,3. The population figures used in the calculat...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1218,resident population that is under one year of ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
df[df['Notes'] == '---']

     Notes State  State Code  Year  Year Code  Deaths  Population  Crude Rate
1174   ---   NaN         NaN   NaN        NaN     NaN         NaN         NaN
1184   ---   NaN         NaN   NaN        NaN     NaN         NaN         NaN
1186   ---   NaN         NaN   NaN        NaN     NaN         NaN         NaN
1188   ---   NaN         NaN   NaN        NaN     NaN         NaN         NaN
1193   ---   NaN         NaN   NaN        NaN     NaN         NaN         NaN

In [11]:
df[df['Notes'] == '---'].index

Index([1174, 1184, 1186, 1188, 1193], dtype='int64')

### EXTRACT METADATA

In [12]:
df_metadata = df.iloc[1174:]
df_metadata.info()

<class 'pandas.DataFrame'>
RangeIndex: 45 entries, 1174 to 1218
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Notes       45 non-null     str
 1   State       0 non-null      str
 2   State Code  0 non-null      float64
 3   Year        0 non-null      float64
 4   Year Code   0 non-null      float64
 5   Deaths      0 non-null      float64
 6   Population  0 non-null      float64
 7   Crude Rate  0 non-null      float64
dtypes: float64(6), str(2)
memory usage: 6.6 KB

### EXTRACT WORKING DATA

In [13]:
df_working = df.iloc[:1174]
df_working.tail()

,Notes,State,State Code,Year,Year Code,Deaths,Population,Crude Rate
1169,NaN,Wyoming,56.0,2018.0,2018.0,5070.0,5.777370e+05,877.56
1170,NaN,Wyoming,56.0,2019.0,2019.0,5121.0,5.787590e+05,884.82
1171,NaN,Wyoming,56.0,2020.0,2020.0,5983.0,5.823280e+05,1027.43
1172,Total,Wyoming,56.0,NaN,NaN,98408.0,1.203514e+07,817.67
1173,Total,NaN,NaN,NaN,NaN,56806341.0,6.746357e+09,842.03

### REMOVE REMAINING NULL VALUES FROM WORKING DATA

In [14]:
df_working.info()

<class 'pandas.DataFrame'>
RangeIndex: 1174 entries, 0 to 1173
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Notes       52 non-null     str
 1   State       1173 non-null   str
 2   State Code  1173 non-null   float64
 3   Year        1122 non-null   float64
 4   Year Code   1122 non-null   float64
 5   Deaths      1174 non-null   float64
 6   Population  1174 non-null   float64
 7   Crude Rate  1174 non-null   float64
dtypes: float64(6), str(2)
memory usage: 84.0 KB

In [15]:
df_working.isna().sum()

Notes         1122
State            1
State Code       1
Year            52
Year Code       52
Deaths           0
Population       0
Crude Rate       0
dtype: int64

In [16]:
df_working[df_working['State'].isna() == True]

,Notes,State,State Code,Year,Year Code,Deaths,Population,Crude Rate
1173,Total,NaN,NaN,NaN,NaN,56806341.0,6.746357e+09,842.03

In [17]:
df_working[df_working['State Code'].isna() == True]

,Notes,State,State Code,Year,Year Code,Deaths,Population,Crude Rate
1173,Total,NaN,NaN,NaN,NaN,56806341.0,6.746357e+09,842.03

In [18]:
df_working_year_null = df_working[df_working['Year'].isna() == True]
df_working_year_null.shape

(52, 8)

In [19]:
df_working_notes_total = df_working[df_working['Notes'] == 'Total']
df_working_notes_total.shape

(52, 8)

In [20]:
df_working_year_null.equals(df_working_notes_total)

True

In [21]:
df_working.info()

<class 'pandas.DataFrame'>
RangeIndex: 1174 entries, 0 to 1173
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Notes       52 non-null     str
 1   State       1173 non-null   str
 2   State Code  1173 non-null   float64
 3   Year        1122 non-null   float64
 4   Year Code   1122 non-null   float64
 5   Deaths      1174 non-null   float64
 6   Population  1174 non-null   float64
 7   Crude Rate  1174 non-null   float64
dtypes: float64(6), str(2)
memory usage: 84.0 KB

In [22]:
df_national_total = df_working[df_working['State'].isna()]

df_state_total = df_working[df_working['Notes'] == 'Total']

df_working = df_working[df_working['Notes'] != 'Total']

### CONFIRM REMOVAL OF MISSING VALUES

In [23]:
df_working.info()

<class 'pandas.DataFrame'>
Index: 1122 entries, 0 to 1171
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Notes       0 non-null      str
 1   State       1122 non-null   str
 2   State Code  1122 non-null   float64
 3   Year        1122 non-null   float64
 4   Year Code   1122 non-null   float64
 5   Deaths      1122 non-null   float64
 6   Population  1122 non-null   float64
 7   Crude Rate  1122 non-null   float64
dtypes: float64(6), str(2)
memory usage: 88.7 KB

### DROP UNNECESSARY COLUMNS

In [24]:
df_working = df_working.drop(columns = 'Notes')

### CHECK WORKING DATA COLUMNS

In [25]:
df_working.info()

<class 'pandas.DataFrame'>
Index: 1122 entries, 0 to 1171
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   State       1122 non-null   str
 1   State Code  1122 non-null   float64
 2   Year        1122 non-null   float64
 3   Year Code   1122 non-null   float64
 4   Deaths      1122 non-null   float64
 5   Population  1122 non-null   float64
 6   Crude Rate  1122 non-null   float64
dtypes: float64(6), str(1)
memory usage: 79.8 KB

### SAVE CLEANED DATA TO PROCESSED FOLDER

In [26]:
print(f"Shape: {df_working.shape}")
print(f"Year range: {df_working['Year'].min()} – {df_working['Year'].max()}")

# write to processed directory
df_working.to_csv(
    '../data/processed/underlying_cause_of_death_1999_2020_processed.csv', 
    index = False
)

print('Saved: ../data/processed/underlying_cause_of_death_1999_2020_processed.csv')

Shape: (1122, 7)
Year range: 1999.0 – 2020.0
Saved: ../data/processed/underlying_cause_of_death_1999_2020_processed.csv

### CONFIRM FILE

In [27]:
os.path.exists('../data/processed/underlying_cause_of_death_1999_2020_processed.csv')

True