## IMPORT LIBRARIES

In [1]:
import pandas as pd
import os

## FLAT FILE DATA INGESTION (STRUCTURED DATASET FROM CDC WONDER)

In [2]:
# load csv file
df = pd.read_csv('../data/raw/multiple_cause_of_death_1999_2020_T400_T401.csv')

## DATA INSPECTION, VALIDATION, CLEANING

In [3]:
# check data
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4177 entries, 0 to 4176
Data columns (total 14 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Notes                         81 non-null     str
 1   State                         4096 non-null   str
 2   State Code                    4096 non-null   float64
 3   Year                          4096 non-null   float64
 4   Year Code                     4096 non-null   float64
 5   Five-Year Age Groups          4096 non-null   str
 6   Five-Year Age Groups Code     4096 non-null   str
 7   Sex                           4096 non-null   str
 8   Sex Code                      4096 non-null   str
 9   Multiple Cause of death       4096 non-null   str
 10  Multiple Cause of death Code  4096 non-null   str
 11  Deaths                        4096 non-null   float64
 12  Population                    4096 non-null   float64
 13  Crude Rate                    4096 non-null   str
dtypes: float64(5), str(9)
memory usage: 662.2 KB

In [4]:
# check first 5 rows
df.head()

,Notes,State,State Code,Year,Year Code,Five-Year Age Groups,Five-Year Age Groups Code,Sex,Sex Code,Multiple Cause of death,Multiple Cause of death Code,Deaths,Population,Crude Rate
0,NaN,Alabama,1.0,2014.0,2014.0,30-34 years,30-34,Male,M,Heroin,T40.1,15.0,151961.0,Unreliable
1,NaN,Alabama,1.0,2014.0,2014.0,35-39 years,35-39,Female,F,Heroin,T40.1,10.0,150784.0,Unreliable
2,NaN,Alabama,1.0,2014.0,2014.0,35-39 years,35-39,Male,M,Heroin,T40.1,12.0,142893.0,Unreliable
3,NaN,Alabama,1.0,2014.0,2014.0,40-44 years,40-44,Male,M,Heroin,T40.1,11.0,152072.0,Unreliable
4,NaN,Alabama,1.0,2015.0,2015.0,25-29 years,25-29,Male,M,Heroin,T40.1,13.0,160487.0,Unreliable

In [5]:
# check last 5 rows
df.tail()

,Notes,State,State Code,Year,Year Code,Five-Year Age Groups,Five-Year Age Groups Code,Sex,Sex Code,Multiple Cause of death,Multiple Cause of death Code,Deaths,Population,Crude Rate
4172,2019 data. Underlying and multiple cause of de...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4173,"unspecified firearm discharge, ICD-10 code X95...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4174,2020.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4175,11. Changes to cause of death classification a...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4176,http://wonder.cdc.gov/wonder/help/mcd.html#ICD...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### CHECK UNIQUE VALUES

In [6]:
# return no. of unique values in 'Notes' column
df['Notes'].nunique()

75

In [7]:
# return list of unique values in 'Notes' column
list(df['Notes'].unique())

[nan,
 '---',
 'Dataset: Multiple Cause of Death, 1999-2020',
 'Query Parameters:',
 'Title: multiple_cause_of_death_1999_2000',
 'MCD - ICD-10 Codes: T40.0 (Opium); T40.1 (Heroin)',
 'Group By: State; Year; Five-Year Age Groups; Sex; Multiple Cause of death',
 'Show Totals: Disabled',
 'Show Zero Values: Disabled',
 'Show Suppressed: True',
 'Calculate Rates Per: 100,000',
 'Rate Options: Default intercensal populations for years 2001-2009 (except Infant Age Groups)',
 'Help: See http://wonder.cdc.gov/wonder/help/mcd.html for more information.',
 'Query Date: May 23, 2026 9:59:18 PM',
 'Suggested Citation: Centers for Disease Control and Prevention, National Center for Health Statistics. National Vital Statistics',
 'System, Mortality 1999-2020 on CDC WONDER Online Database, released in 2021. Data are from the Multiple Cause of Death Files,',
 '1999-2020, as compiled from data provided by the 57 vital statistics jurisdictions through the Vital Statistics Cooperative',
 'Program. Accessed at http://wonder.cdc.gov/mcd-icd10.html on May 23, 2026 9:59:18 PM',
 'Messages:',
 '1. The full results are too long to be displayed. Due to suppression constraints rows that are zero, suppressed or a total will',
 'not be available.',
 'Footnotes:',
 '1. Totals and sub-totals show the frequency of the selected causes of death, which may be greater than the number of deaths.',
 'Note that any single death record may have up to 20 causes. More information.',
 'Caveats:',
 '1. As of April 3, 2017, the underlying cause of death has been revised for 125 deaths in 2014. More information:',
 'http://wonder.cdc.gov/wonder/help/mcd.html#2014-Revision.',
 '2. Circumstances in Georgia for the years 2008 and 2009 have resulted in unusually high death counts for the ICD-10 cause of',
 'death code R99, "Other ill-defined and unspecified causes of mortality." Caution should be used in interpreting these data.',
 'More information: http://wonder.cdc.gov/wonder/help/mcd.html#Georgia-Reporting-Anomalies.',
 '3. Circumstances in New Jersey for the year 2009 have resulted in unusually high death counts for the ICD-10 cause of death code',
 'R99, "Other ill-defined and unspecified causes of mortality" and therefore unusually low death counts in other ICD-10 codes,',
 'most notably R95, "Sudden Infant Death Syndrome" and X40-X49, "Unintentional poisoning." Caution should be used in',
 'interpreting these data. More information: http://wonder.cdc.gov/wonder/help/mcd.html#New-Jersey-Reporting-Anomalies.',
 '4. Circumstances in California resulted in unusually high death counts for the ICD-10 cause of death code R99, "Other',
 'ill-defined and unspecified causes of mortality" for deaths occurring in years 2000 and 2001. Caution should be used in',
 'interpreting these data. More information: http://wonder.cdc.gov/wonder/help/mcd.html#California-Reporting-Anomalies.',
 '5. Death rates are flagged as Unreliable when the rate is calculated with a numerator of 20 or less. More information:',
 'http://wonder.cdc.gov/wonder/help/mcd.html#Unreliable.',
 '6. Deaths of persons with Age "Not Stated" are included in "All" counts and rates, but are not distributed among age groups,',
 'so are not included in age-specific counts, age-specific rates or in any age-adjusted rates. More information:',
 'http://wonder.cdc.gov/wonder/help/mcd.html#Not Stated.',
 '7. The population figures for year 2020 are bridged-race estimates of the July 1 resident population, from the Vintage 2020',
 'postcensal series released by NCHS on September 22, 2021. The population figures for year 2019 are bridged-race estimates of the',
 'July 1 resident population, from the Vintage 2019 postcensal series released by NCHS on July 9, 2020. The population figures for',
 'year 2018 are bridged-race estimates of the July 1 resident population, from the Vintage 2018 postcensal series released by NCHS',
 'on June 25, 2019. The population figures for year 2017 are bridged-race estimates of the July 1 resident population, from the',
 'Vintage 2017 postcensal series released by NCHS on June 27, 2018. The population figures for year 2016 are bridged-race',
 'estimates of the July 1 resident population, from the Vintage 2016 postcensal series released by NCHS on June 26, 2017. The',
 'population figures for year 2015 are bridged-race estimates of the July 1 resident population, from the Vintage 2015 postcensal',
 'series released by NCHS on June 28, 2016. The population figures for year 2014 are bridged-race estimates of the July 1 resident',
 'population, from the Vintage 2014 postcensal series released by NCHS on June 30, 2015. The population figures for year 2013 are',
 'bridged-race estimates of the July 1 resident population, from the Vintage 2013 postcensal series released by NCHS on June 26,',
 '2014. The population figures for year 2012 are bridged-race estimates of the July 1 resident population, from the Vintage 2012',
 'postcensal series released by NCHS on June 13, 2013. Population figures for 2011 are bridged-race estimates of the July 1',
 'resident population, from the county-level postcensal Vintage 2011 series released by NCHS on July 18, 2012. Population figures',
 'for 2010 are April 1 Census counts. The population figures for years 2001 - 2009, are bridged-race estimates of the July 1',
 'resident population, from the revised intercensal county-level 2000 - 2009 series released by NCHS on October 26, 2012.',
 'Population figures for 2000 are April 1 Census counts. Population figures for 1999 are from the 1990-1999 intercensal series of',
 'July 1 estimates. Population figures for Infant Age Groups are the number of live births. <br/><b>Note:</b> Rates and population',
 'figures for years 2001 - 2009 differ slightly from previously published reports, due to use of the population estimates which',
 'were available at the time of release.',
 "8. The population figures used in the calculation of death rates for the age group 'under 1 year' are the estimates of the",
 'resident population that is under one year of age. More information: http://wonder.cdc.gov/wonder/help/mcd.html#Age Group.',
 '9. Beginning with the 2018 data, changes have been implemented that affect the counts for ICD-10 cause of death codes O00-O99',
 'compared to previous practice. In addition, data for the cause of death codes O00-O99 for 2003 through 2017 reflect differences',
 'in information available to individual states and probable errors. Caution should be used in interpreting these data. More',
 'information can be found at: https://www.cdc.gov/nchs/maternal-mortality/.',
 '10. On March 11, 2021, the 2019 mortality data on CDC WONDER was updated with the 2019 mortality data updated by NCHS on March',
 '4, 2021 to include corrected information for residents of Texas affecting 5 records previously coded to cause code *U01.4,',
 'Terrorism involving firearms (homicide). The underlying and multiple cause of death codes for 5 records were corrected in the',
 '2019 data. Underlying and multiple cause of death codes for those 5 records were recoded to Assault (homicide) by other and',
 'unspecified firearm discharge, ICD-10 code X95. The corrected final death records replaces the data released on December 22,',
 '2020.',
 '11. Changes to cause of death classification affect reporting trends. More information:',
 'http://wonder.cdc.gov/wonder/help/mcd.html#ICD-10 Changes.']

### CHECK FOR MISSING VALUES

In [8]:
# return data where 'Notes' column has text
df[df['Notes'].notna()]

,Notes,State,State Code,Year,Year Code,Five-Year Age Groups,Five-Year Age Groups Code,Sex,Sex Code,Multiple Cause of death,Multiple Cause of death Code,Deaths,Population,Crude Rate
4096,---,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4097,"Dataset: Multiple Cause of Death, 1999-2020",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4098,Query Parameters:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4099,Title: multiple_cause_of_death_1999_2000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4100,MCD - ICD-10 Codes: T40.0 (Opium); T40.1 (Heroin),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4172,2019 data. Underlying and multiple cause of de...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4173,"unspecified firearm discharge, ICD-10 code X95...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4174,2020.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4175,11. Changes to cause of death classification a...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4176,http://wonder.cdc.gov/wonder/help/mcd.html#ICD...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
# return indexes of rows where 'Notes' column has text
df[df['Notes'].notna()].index

RangeIndex(start=4096, stop=4177, step=1)

### EXTRACT METADATA

In [10]:
# return dataframe of rows where 'Notes' column has text
df_metadata = df[df['Notes'].notna()]
df_metadata

,Notes,State,State Code,Year,Year Code,Five-Year Age Groups,Five-Year Age Groups Code,Sex,Sex Code,Multiple Cause of death,Multiple Cause of death Code,Deaths,Population,Crude Rate
4096,---,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4097,"Dataset: Multiple Cause of Death, 1999-2020",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4098,Query Parameters:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4099,Title: multiple_cause_of_death_1999_2000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4100,MCD - ICD-10 Codes: T40.0 (Opium); T40.1 (Heroin),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4172,2019 data. Underlying and multiple cause of de...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4173,"unspecified firearm discharge, ICD-10 code X95...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4174,2020.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4175,11. Changes to cause of death classification a...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4176,http://wonder.cdc.gov/wonder/help/mcd.html#ICD...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
# check df_metadata
df_metadata.info()

<class 'pandas.DataFrame'>
RangeIndex: 81 entries, 4096 to 4176
Data columns (total 14 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Notes                         81 non-null     str
 1   State                         0 non-null      str
 2   State Code                    0 non-null      float64
 3   Year                          0 non-null      float64
 4   Year Code                     0 non-null      float64
 5   Five-Year Age Groups          0 non-null      str
 6   Five-Year Age Groups Code     0 non-null      str
 7   Sex                           0 non-null      str
 8   Sex Code                      0 non-null      str
 9   Multiple Cause of death       0 non-null      str
 10  Multiple Cause of death Code  0 non-null      str
 11  Deaths                        0 non-null      float64
 12  Population                    0 non-null      float64
 13  Crude Rate                    0 non-null      str
dtypes: float64(5), str(9)
memory usage: 16.0 KB

### EXTRACT WORKING DATA

In [12]:
# return df_working excluding rows where 'Notes' column has text
# check last 5 rows
df_working = df.iloc[:4096]
df_working.tail()

,Notes,State,State Code,Year,Year Code,Five-Year Age Groups,Five-Year Age Groups Code,Sex,Sex Code,Multiple Cause of death,Multiple Cause of death Code,Deaths,Population,Crude Rate
4091,NaN,Wisconsin,55.0,2020.0,2020.0,45-49 years,45-49,Female,F,Heroin,T40.1,12.0,165855.0,Unreliable
4092,NaN,Wisconsin,55.0,2020.0,2020.0,45-49 years,45-49,Male,M,Heroin,T40.1,19.0,168550.0,Unreliable
4093,NaN,Wisconsin,55.0,2020.0,2020.0,50-54 years,50-54,Male,M,Heroin,T40.1,20.0,182637.0,10.95
4094,NaN,Wisconsin,55.0,2020.0,2020.0,55-59 years,55-59,Male,M,Heroin,T40.1,16.0,204597.0,Unreliable
4095,NaN,Wisconsin,55.0,2020.0,2020.0,65-69 years,65-69,Male,M,Heroin,T40.1,10.0,170341.0,Unreliable

In [13]:
# check df_working
df_working.info()

<class 'pandas.DataFrame'>
RangeIndex: 4096 entries, 0 to 4095
Data columns (total 14 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Notes                         0 non-null      str
 1   State                         4096 non-null   str
 2   State Code                    4096 non-null   float64
 3   Year                          4096 non-null   float64
 4   Year Code                     4096 non-null   float64
 5   Five-Year Age Groups          4096 non-null   str
 6   Five-Year Age Groups Code     4096 non-null   str
 7   Sex                           4096 non-null   str
 8   Sex Code                      4096 non-null   str
 9   Multiple Cause of death       4096 non-null   str
 10  Multiple Cause of death Code  4096 non-null   str
 11  Deaths                        4096 non-null   float64
 12  Population                    4096 non-null   float64
 13  Crude Rate                    4096 non-null   str
dtypes: float64(5), str(9)
memory usage: 646.3 KB

### DROP UNNECESSARY COLUMNS

In [14]:
# drop 'Notes' column from df_working
df_working = df_working.drop(columns = 'Notes')

### CHECK WORKING DATA COLUMNS

In [15]:
# check df_working
df_working.info()

<class 'pandas.DataFrame'>
RangeIndex: 4096 entries, 0 to 4095
Data columns (total 13 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   State                         4096 non-null   str
 1   State Code                    4096 non-null   float64
 2   Year                          4096 non-null   float64
 3   Year Code                     4096 non-null   float64
 4   Five-Year Age Groups          4096 non-null   str
 5   Five-Year Age Groups Code     4096 non-null   str
 6   Sex                           4096 non-null   str
 7   Sex Code                      4096 non-null   str
 8   Multiple Cause of death       4096 non-null   str
 9   Multiple Cause of death Code  4096 non-null   str
 10  Deaths                        4096 non-null   float64
 11  Population                    4096 non-null   float64
 12  Crude Rate                    4096 non-null   str
dtypes: float64(5), str(8)
memory usage: 613.8 KB

### CREATE A FUNCTION TO CLEAN DATA

In [16]:
# define function to clean data
def load_cdc_csv(filepath: str) -> pd.DataFrame:

    # load csv as string
    df = pd.read_csv(filepath, dtype = str)

    # CDC WONDER appends metadata below data rows
    # valid data rows have NaN in 'Notes' column
    # return index of first row with metadata
    cutoff = df[df['Notes'].notna()].index[0]

    # drop rows with metadata
    df_clean = df.iloc[:cutoff]

    # drop 'Notes' column
    df_clean = df_clean.drop(columns = 'Notes')
    
    return df_clean

### LEVERAGE FUNCTION TO LOAD & CLEAN MULTIPLE DATA FILES
### CONCATENATE AND SAVE CLEANED DATA TO PROCESSED FOLDER

In [17]:
# load csv files
files = [
    '../data/raw/multiple_cause_of_death_1999_2020_T400_T401.csv',
    '../data/raw/multiple_cause_of_death_1999_2020_T402.csv',
    '../data/raw/multiple_cause_of_death_1999_2020_T403_T404.csv',
    '../data/raw/multiple_cause_of_death_1999_2020_T405_T406.csv'
]

# load process csv files into list
df_combine = [load_cdc_csv(f) for f in files]

# concatenate
df_combine = pd.concat(df_combine, ignore_index=True)

print(f"Shape: {df_combine.shape}")
print(f"Unique ICD codes: {df_combine['Multiple Cause of death Code'].unique()}")
print(f"Year range: {df_combine['Year'].min()} – {df_combine['Year'].max()}")

# write to processed directory
df_combine.to_csv(
    '../data/processed/multiple_cause_of_death_1999_2020_processed.csv', 
    index = False
)

print('Saved: ../data/processed/multiple_cause_of_death_1999_2020_processed.csv')

Shape: (23011, 13)
Unique ICD codes: <ArrowStringArray>
['T40.1', 'T40.2', 'T40.5', 'T40.6', 'T40.3', 'T40.4']
Length: 6, dtype: str
Year range: 1999 – 2020
Saved: ../data/processed/multiple_cause_of_death_1999_2020_processed.csv

### CONFIRM FILE

In [18]:
os.path.exists('../data/processed/multiple_cause_of_death_1999_2020_processed.csv')

True