## 1. Import Libraries

In [1]:
import pandas as pd
import os

## 2. Load Data - Flat File Ingestion from CDC Wonder

In [2]:
df_mcd = pd.read_csv('../data/processed/multiple_cause_of_death_1999_2020_processed.csv')

## 3. Inspect, Validate, Clean

In [3]:
df_mcd.info()

<class 'pandas.DataFrame'>
RangeIndex: 23011 entries, 0 to 23010
Data columns (total 13 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   State                         23011 non-null  str
 1   State Code                    23011 non-null  int64
 2   Year                          23011 non-null  int64
 3   Year Code                     23011 non-null  int64
 4   Five-Year Age Groups          23011 non-null  str
 5   Five-Year Age Groups Code     23011 non-null  str
 6   Sex                           23011 non-null  str
 7   Sex Code                      23011 non-null  str
 8   Multiple Cause of death       23011 non-null  str
 9   Multiple Cause of death Code  23011 non-null  str
 10  Deaths                        23011 non-null  int64
 11  Population                    23011 non-null  int64
 12  Crude Rate                    23011 non-null  str
dtypes: int64(5), str(8)
memory usage: 3.5 MB

In [4]:
df_mcd.describe()

         State Code          Year     Year Code        Deaths    Population
count  23011.000000  23011.000000  23011.000000  23011.000000  2.301100e+04
mean      29.758420   2012.673200   2012.673200     28.495850  4.022747e+05
std       15.485556      5.833286      5.833286     31.616413  3.182663e+05
min        1.000000   1999.000000   1999.000000     10.000000  9.685000e+03
25%       17.000000   2008.000000   2008.000000     13.000000  1.985105e+05
50%       32.000000   2014.000000   2014.000000     18.000000  2.997170e+05
75%       42.000000   2018.000000   2018.000000     31.000000  4.861870e+05
max       55.000000   2020.000000   2020.000000    605.000000  1.617117e+06

In [5]:
df_mcd.head()

,State,State Code,Year,Year Code,Five-Year Age Groups,Five-Year Age Groups Code,Sex,Sex Code,Multiple Cause of death,Multiple Cause of death Code,Deaths,Population,Crude Rate
0,Alabama,1,2014,2014,30-34 years,30-34,Male,M,Heroin,T40.1,15,151961,Unreliable
1,Alabama,1,2014,2014,35-39 years,35-39,Female,F,Heroin,T40.1,10,150784,Unreliable
2,Alabama,1,2014,2014,35-39 years,35-39,Male,M,Heroin,T40.1,12,142893,Unreliable
3,Alabama,1,2014,2014,40-44 years,40-44,Male,M,Heroin,T40.1,11,152072,Unreliable
4,Alabama,1,2015,2015,25-29 years,25-29,Male,M,Heroin,T40.1,13,160487,Unreliable

In [6]:
df_mcd.tail()

,State,State Code,Year,Year Code,Five-Year Age Groups,Five-Year Age Groups Code,Sex,Sex Code,Multiple Cause of death,Multiple Cause of death Code,Deaths,Population,Crude Rate
23006,Wisconsin,55,2020,2020,55-59 years,55-59,Female,F,Other synthetic narcotics,T40.4,25,209450,11.94
23007,Wisconsin,55,2020,2020,55-59 years,55-59,Male,M,Other synthetic narcotics,T40.4,52,204597,25.42
23008,Wisconsin,55,2020,2020,60-64 years,60-64,Female,F,Other synthetic narcotics,T40.4,13,205874,Unreliable
23009,Wisconsin,55,2020,2020,60-64 years,60-64,Male,M,Other synthetic narcotics,T40.4,42,199932,21.01
23010,Wisconsin,55,2020,2020,65-69 years,65-69,Male,M,Other synthetic narcotics,T40.4,14,170341,Unreliable

### Check missing values across all columns

In [7]:
df_mcd.isna().sum()

State                           0
State Code                      0
Year                            0
Year Code                       0
Five-Year Age Groups            0
Five-Year Age Groups Code       0
Sex                             0
Sex Code                        0
Multiple Cause of death         0
Multiple Cause of death Code    0
Deaths                          0
Population                      0
Crude Rate                      0
dtype: int64

### Check duplicate rows

In [8]:
df_mcd.duplicated().sum()

np.int64(0)

### Check unique values across all columns

In [9]:
df_mcd.nunique()

State                             45
State Code                        45
Year                              22
Year Code                         22
Five-Year Age Groups              14
Five-Year Age Groups Code         14
Sex                                2
Sex Code                           2
Multiple Cause of death            6
Multiple Cause of death Code       6
Deaths                           282
Population                      9071
Crude Rate                      3394
dtype: int64

\* Looks like `State` is missing 5 states \*

### Check unique values in `State`

In [10]:
df_mcd['State'].unique()

<ArrowStringArray>
[             'Alabama',               'Alaska',              'Arizona',
           'California',             'Colorado',          'Connecticut',
             'Delaware', 'District of Columbia',              'Florida',
              'Georgia',             'Illinois',              'Indiana',
                 'Iowa',             'Kentucky',            'Louisiana',
                'Maine',             'Maryland',        'Massachusetts',
             'Michigan',            'Minnesota',          'Mississippi',
             'Missouri',               'Nevada',        'New Hampshire',
           'New Jersey',           'New Mexico',             'New York',
       'North Carolina',                 'Ohio',             'Oklahoma',
               'Oregon',         'Pennsylvania',         'Rhode Island',
       'South Carolina',            'Tennessee',                'Texas',
                 'Utah',              'Vermont',             'Virginia',
           'Washington',        'West Virginia',            'Wisconsin',
             'Arkansas',               'Kansas',              'Montana']
Length: 45, dtype: str

### Check against 50 states + Disctrict of Columbia

In [11]:
expected_states = [
    'Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California', 'Colorado',
    'Connecticut', 'Delaware', 'District of Columbia', 'Florida', 'Georgia',
    'Hawaii', 'Idaho', 'Illinois', 'Indiana', 'Iowa', 'Kansas', 'Kentucky',
    'Louisiana', 'Maine', 'Maryland', 'Massachusetts', 'Michigan', 'Minnesota',
    'Mississippi', 'Missouri', 'Montana', 'Nebraska', 'Nevada', 'New Hampshire',
    'New Jersey', 'New Mexico', 'New York', 'North Carolina', 'North Dakota',
    'Ohio', 'Oklahoma', 'Oregon', 'Pennsylvania', 'Rhode Island', 'South Carolina',
    'South Dakota', 'Tennessee', 'Texas', 'Utah', 'Vermont', 'Virginia',
    'Washington', 'West Virginia', 'Wisconsin', 'Wyoming'
]
print(f"Total Count of 50 States + Disctrict of Columbia: {len(expected_states)}")

Total Count of 50 States + Disctrict of Columbia: 51

In [12]:
actual_states = df_mcd['State'].unique()

In [13]:
missing_states = [state for state in expected_states if state not in actual_states]
missing_states

['Hawaii', 'Idaho', 'Nebraska', 'North Dakota', 'South Dakota', 'Wyoming']

**Important:**
CDC WONDER suppresse death counts < 10 to protect individual privacy. Reference: https://wonder.cdc.gov/wonder/help/mcd.html

In [14]:
df_mcd.info()

<class 'pandas.DataFrame'>
RangeIndex: 23011 entries, 0 to 23010
Data columns (total 13 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   State                         23011 non-null  str
 1   State Code                    23011 non-null  int64
 2   Year                          23011 non-null  int64
 3   Year Code                     23011 non-null  int64
 4   Five-Year Age Groups          23011 non-null  str
 5   Five-Year Age Groups Code     23011 non-null  str
 6   Sex                           23011 non-null  str
 7   Sex Code                      23011 non-null  str
 8   Multiple Cause of death       23011 non-null  str
 9   Multiple Cause of death Code  23011 non-null  str
 10  Deaths                        23011 non-null  int64
 11  Population                    23011 non-null  int64
 12  Crude Rate                    23011 non-null  str
dtypes: int64(5), str(8)
memory usage: 3.5 MB

### Check unique values in  `Year`

In [15]:
sorted(df_mcd['Year'].unique())

[np.int64(1999),
 np.int64(2000),
 np.int64(2001),
 np.int64(2002),
 np.int64(2003),
 np.int64(2004),
 np.int64(2005),
 np.int64(2006),
 np.int64(2007),
 np.int64(2008),
 np.int64(2009),
 np.int64(2010),
 np.int64(2011),
 np.int64(2012),
 np.int64(2013),
 np.int64(2014),
 np.int64(2015),
 np.int64(2016),
 np.int64(2017),
 np.int64(2018),
 np.int64(2019),
 np.int64(2020)]

In [16]:
df_mcd.nunique()

State                             45
State Code                        45
Year                              22
Year Code                         22
Five-Year Age Groups              14
Five-Year Age Groups Code         14
Sex                                2
Sex Code                           2
Multiple Cause of death            6
Multiple Cause of death Code       6
Deaths                           282
Population                      9071
Crude Rate                      3394
dtype: int64

### Check `Five-Year Age Groups` column

In [17]:
sorted(df_mcd['Five-Year Age Groups'].unique())

['15-19 years',
 '20-24 years',
 '25-29 years',
 '30-34 years',
 '35-39 years',
 '40-44 years',
 '45-49 years',
 '50-54 years',
 '55-59 years',
 '60-64 years ',
 '65-69 years',
 '70-74 years',
 '75-79 years',
 '80-84 years']

### Remove trailing whitespace in `Five-Year Age Groups`

In [18]:
df_mcd['Five-Year Age Groups'] = df_mcd['Five-Year Age Groups'].str.strip()
sorted(df_mcd['Five-Year Age Groups'].unique())

['15-19 years',
 '20-24 years',
 '25-29 years',
 '30-34 years',
 '35-39 years',
 '40-44 years',
 '45-49 years',
 '50-54 years',
 '55-59 years',
 '60-64 years',
 '65-69 years',
 '70-74 years',
 '75-79 years',
 '80-84 years']

### Check `Sex` column

In [19]:
df_mcd['Sex'].unique()

<ArrowStringArray>
['Male', 'Female']
Length: 2, dtype: str

### Check `Multiple Cause of death` column

In [20]:
df_mcd['Multiple Cause of death'].unique()

<ArrowStringArray>
[                         'Heroin',                   'Other opioids',
                         'Cocaine', 'Other and unspecified narcotics',
                       'Methadone',       'Other synthetic narcotics']
Length: 6, dtype: str

In [21]:
df_mcd['Multiple Cause of death Code'].unique()

<ArrowStringArray>
['T40.1', 'T40.2', 'T40.5', 'T40.6', 'T40.3', 'T40.4']
Length: 6, dtype: str

In [22]:
print(df_mcd[['Multiple Cause of death', 'Multiple Cause of death Code']].drop_duplicates())

               Multiple Cause of death Multiple Cause of death Code
0                               Heroin                        T40.1
4096                     Other opioids                        T40.2
10908                          Cocaine                        T40.5
10934  Other and unspecified narcotics                        T40.6
17172                        Methadone                        T40.3
17183        Other synthetic narcotics                        T40.4

In [23]:
df_mcd.nunique()

State                             45
State Code                        45
Year                              22
Year Code                         22
Five-Year Age Groups              14
Five-Year Age Groups Code         14
Sex                                2
Sex Code                           2
Multiple Cause of death            6
Multiple Cause of death Code       6
Deaths                           282
Population                      9071
Crude Rate                      3394
dtype: int64

### Check summary statistics for `Deaths`, `Population`, and `Crude Rate`

In [24]:
df_mcd['Deaths'].describe()

count    23011.000000
mean        28.495850
std         31.616413
min         10.000000
25%         13.000000
50%         18.000000
75%         31.000000
max        605.000000
Name: Deaths, dtype: float64

In [25]:
df_mcd['Population'].describe()

count    2.301100e+04
mean     4.022747e+05
std      3.182663e+05
min      9.685000e+03
25%      1.985105e+05
50%      2.997170e+05
75%      4.861870e+05
max      1.617117e+06
Name: Population, dtype: float64

In [26]:
df_mcd['Crude Rate'].describe()

count          23011
unique          3394
top       Unreliable
freq           12369
Name: Crude Rate, dtype: object

### Looks like `Crude Rate` has string values

In [27]:
df_mcd['Crude Rate'].dtype

In [28]:
df_mcd['Crude Rate'].head()

0    Unreliable
1    Unreliable
2    Unreliable
3    Unreliable
4    Unreliable
Name: Crude Rate, dtype: str

In [29]:
df_mcd['Crude Rate'].tail()

23006         11.94
23007         25.42
23008    Unreliable
23009         21.01
23010    Unreliable
Name: Crude Rate, dtype: str

### Convert `Crude Rate` to numerical values. Convert non-numerical values to `NaN`

In [30]:
df_mcd['Crude Rate'] = pd.to_numeric(df_mcd['Crude Rate'], errors = 'coerce')
df_mcd['Crude Rate'].dtype

dtype('float64')

#### Return count of `NaN` values

In [31]:
df_mcd['Crude Rate'].isna().sum()

np.int64(12369)

### Return % of `NaN` values in `Crude Rate`

In [32]:
crude_rate_null_pct = (df_mcd['Crude Rate'].isna().sum() / df_mcd.shape[0] * 100).round(2)
print(f" Percent of null values in Crude Rate column: {crude_rate_null_pct}")

 Percent of null values in Crude Rate column: 53.75

**Important:** Crude Rate = Count / Population * 100,000. Rates are marked as "unreliable" when the death count is less than 20. Reference: https://wonder.cdc.gov/wonder/help/mcd.html

### `Crude Rate` is unusable given that has ~54% `NaN` values

### Create custom `Crude Rate Calculated` column

In [33]:
df_mcd['Crude Rate Calculated'] = (df_mcd['Deaths'] / df_mcd['Population'] * 100000).round(2)

### Confirm `Crude Rate Calculated`

In [34]:
df_mcd.info()

<class 'pandas.DataFrame'>
RangeIndex: 23011 entries, 0 to 23010
Data columns (total 14 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   State                         23011 non-null  str
 1   State Code                    23011 non-null  int64
 2   Year                          23011 non-null  int64
 3   Year Code                     23011 non-null  int64
 4   Five-Year Age Groups          23011 non-null  str
 5   Five-Year Age Groups Code     23011 non-null  str
 6   Sex                           23011 non-null  str
 7   Sex Code                      23011 non-null  str
 8   Multiple Cause of death       23011 non-null  str
 9   Multiple Cause of death Code  23011 non-null  str
 10  Deaths                        23011 non-null  int64
 11  Population                    23011 non-null  int64
 12  Crude Rate                    10642 non-null  float64
 13  Crude Rate Calculated         23011 non-null  float64
dtypes: float64(2), int64(5), str(7)
memory usage: 3.5 MB

In [35]:
df_mcd['Crude Rate Calculated'].isna().sum()

np.int64(0)

In [36]:
df_mcd['Crude Rate Calculated'].nunique()

3829

### Columns we can safely drop `Year Code`, `Five-Year Age Groups Code`, `Sex Code`, `Crude Rate` - keeping `State Code` in case Tableau can read it

In [37]:
df_mcd_clean = df_mcd.drop(
    columns = [
        'Year Code', 
        'Five-Year Age Groups Code', 
        'Sex Code', 
        'Crude Rate'
    ]
)

### Check `df_mcd_clean`

In [38]:
df_mcd_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 23011 entries, 0 to 23010
Data columns (total 10 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   State                         23011 non-null  str
 1   State Code                    23011 non-null  int64
 2   Year                          23011 non-null  int64
 3   Five-Year Age Groups          23011 non-null  str
 4   Sex                           23011 non-null  str
 5   Multiple Cause of death       23011 non-null  str
 6   Multiple Cause of death Code  23011 non-null  str
 7   Deaths                        23011 non-null  int64
 8   Population                    23011 non-null  int64
 9   Crude Rate Calculated         23011 non-null  float64
dtypes: float64(1), int64(4), str(5)
memory usage: 2.7 MB

Data Inspection, Validation, Complete!

In [39]:
print(f"Shape: {df_mcd_clean.shape}")
print(f"Unique ICD codes: {df_mcd_clean['Multiple Cause of death Code'].unique()}")
print(f"Year range: {df_mcd_clean['Year'].min()} – {df_mcd_clean['Year'].max()}")

# write to processed directory
df_mcd_clean.to_csv(
    '../data/processed/multiple_cause_of_death_1999_2020_clean.csv', 
    index = False
)

print('Saved: ../data/processed/multiple_cause_of_death_1999_2020_clean.csv')

Shape: (23011, 10)
Unique ICD codes: <ArrowStringArray>
['T40.1', 'T40.2', 'T40.5', 'T40.6', 'T40.3', 'T40.4']
Length: 6, dtype: str
Year range: 1999 – 2020
Saved: ../data/processed/multiple_cause_of_death_1999_2020_clean.csv

In [40]:
os.path.exists('../data/processed/multiple_cause_of_death_1999_2020_clean.csv')

True